"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Coupon = exports.PhoneViewLog = exports.ProfileView = exports.Notification = exports.Waitlist = exports.SuccessStory = exports.Report = exports.Block = exports.Payment = exports.Subscription = exports.Plan = exports.Message = exports.Match = exports.Interest = exports.Badge = exports.EducationCareer = exports.LocationLifestyle = exports.HoroscopeDetails = exports.FamilyDetails = exports.UserDraft = exports.UserPhoto = exports.UserPreference = exports.UserProfile = exports.User = exports.Rasi = exports.Laknam = exports.Gothram = exports.Star = exports.IncomeRange = exports.Currency = exports.Occupation = exports.EmploymentType = exports.Education = exports.Height = exports.Caste = exports.Religion = exports.MotherTongue = exports.City = exports.State = exports.Country = exports.sequelize = void 0;
var db_postgres_1 = require("../../config/db.postgres");
Object.defineProperty(exports, "sequelize", { enumerable: true, get: function () { return db_postgres_1.sequelize; } });
// Master Models
var Country_1 = require("./master/Country");
Object.defineProperty(exports, "Country", { enumerable: true, get: function () { return Country_1.Country; } });
var State_1 = require("./master/State");
Object.defineProperty(exports, "State", { enumerable: true, get: function () { return State_1.State; } });
var City_1 = require("./master/City");
Object.defineProperty(exports, "City", { enumerable: true, get: function () { return City_1.City; } });
var MotherTongue_1 = require("./master/MotherTongue");
Object.defineProperty(exports, "MotherTongue", { enumerable: true, get: function () { return MotherTongue_1.MotherTongue; } });
var Religion_1 = require("./master/Religion");
Object.defineProperty(exports, "Religion", { enumerable: true, get: function () { return Religion_1.Religion; } });
var Caste_1 = require("./master/Caste");
Object.defineProperty(exports, "Caste", { enumerable: true, get: function () { return Caste_1.Caste; } });
var Height_1 = require("./master/Height");
Object.defineProperty(exports, "Height", { enumerable: true, get: function () { return Height_1.Height; } });
var Education_1 = require("./master/Education");
Object.defineProperty(exports, "Education", { enumerable: true, get: function () { return Education_1.Education; } });
var EmploymentType_1 = require("./master/EmploymentType");
Object.defineProperty(exports, "EmploymentType", { enumerable: true, get: function () { return EmploymentType_1.EmploymentType; } });
var Occupation_1 = require("./master/Occupation");
Object.defineProperty(exports, "Occupation", { enumerable: true, get: function () { return Occupation_1.Occupation; } });
var Currency_1 = require("./master/Currency");
Object.defineProperty(exports, "Currency", { enumerable: true, get: function () { return Currency_1.Currency; } });
var IncomeRange_1 = require("./master/IncomeRange");
Object.defineProperty(exports, "IncomeRange", { enumerable: true, get: function () { return IncomeRange_1.IncomeRange; } });
var Star_1 = require("./master/Star");
Object.defineProperty(exports, "Star", { enumerable: true, get: function () { return Star_1.Star; } });
var Gothram_1 = require("./master/Gothram");
Object.defineProperty(exports, "Gothram", { enumerable: true, get: function () { return Gothram_1.Gothram; } });
var Laknam_1 = require("./master/Laknam");
Object.defineProperty(exports, "Laknam", { enumerable: true, get: function () { return Laknam_1.Laknam; } });
var Rasi_1 = require("./master/Rasi");
Object.defineProperty(exports, "Rasi", { enumerable: true, get: function () { return Rasi_1.Rasi; } });
// Core Models
var User_1 = require("./User");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return User_1.User; } });
var UserProfile_1 = require("./UserProfile");
Object.defineProperty(exports, "UserProfile", { enumerable: true, get: function () { return UserProfile_1.UserProfile; } });
var UserPreference_1 = require("./UserPreference");
Object.defineProperty(exports, "UserPreference", { enumerable: true, get: function () { return UserPreference_1.UserPreference; } });
var UserPhoto_1 = require("./UserPhoto");
Object.defineProperty(exports, "UserPhoto", { enumerable: true, get: function () { return UserPhoto_1.UserPhoto; } });
var UserDraft_1 = require("./UserDraft");
Object.defineProperty(exports, "UserDraft", { enumerable: true, get: function () { return UserDraft_1.UserDraft; } });
var FamilyDetails_1 = require("./FamilyDetails");
Object.defineProperty(exports, "FamilyDetails", { enumerable: true, get: function () { return FamilyDetails_1.FamilyDetails; } });
var HoroscopeDetails_1 = require("./HoroscopeDetails");
Object.defineProperty(exports, "HoroscopeDetails", { enumerable: true, get: function () { return HoroscopeDetails_1.HoroscopeDetails; } });
var LocationLifestyle_1 = require("./LocationLifestyle");
Object.defineProperty(exports, "LocationLifestyle", { enumerable: true, get: function () { return LocationLifestyle_1.LocationLifestyle; } });
var EducationCareer_1 = require("./EducationCareer");
Object.defineProperty(exports, "EducationCareer", { enumerable: true, get: function () { return EducationCareer_1.EducationCareer; } });
var Badge_1 = require("./Badge");
Object.defineProperty(exports, "Badge", { enumerable: true, get: function () { return Badge_1.Badge; } });
// Action Models
var Interest_1 = require("./Interest");
Object.defineProperty(exports, "Interest", { enumerable: true, get: function () { return Interest_1.Interest; } });
var Match_1 = require("./Match");
Object.defineProperty(exports, "Match", { enumerable: true, get: function () { return Match_1.Match; } });
var Message_1 = require("./Message");
Object.defineProperty(exports, "Message", { enumerable: true, get: function () { return Message_1.Message; } });
var Plan_1 = require("./Plan");
Object.defineProperty(exports, "Plan", { enumerable: true, get: function () { return Plan_1.Plan; } });
var Subscription_1 = require("./Subscription");
Object.defineProperty(exports, "Subscription", { enumerable: true, get: function () { return Subscription_1.Subscription; } });
var Payment_1 = require("./Payment");
Object.defineProperty(exports, "Payment", { enumerable: true, get: function () { return Payment_1.Payment; } });
var Waitlist_1 = require("./Waitlist");
Object.defineProperty(exports, "Waitlist", { enumerable: true, get: function () { return Waitlist_1.Waitlist; } });
var Notification_1 = require("./Notification");
Object.defineProperty(exports, "Notification", { enumerable: true, get: function () { return Notification_1.Notification; } });
var ProfileView_1 = require("./ProfileView");
Object.defineProperty(exports, "ProfileView", { enumerable: true, get: function () { return ProfileView_1.ProfileView; } });
var PhoneViewLog_1 = require("./PhoneViewLog");
Object.defineProperty(exports, "PhoneViewLog", { enumerable: true, get: function () { return PhoneViewLog_1.PhoneViewLog; } });
var Coupon_1 = require("./Coupon");
Object.defineProperty(exports, "Coupon", { enumerable: true, get: function () { return Coupon_1.Coupon; } });
// Moderation
var Moderation_1 = require("./Moderation");
Object.defineProperty(exports, "Block", { enumerable: true, get: function () { return Moderation_1.Block; } });
Object.defineProperty(exports, "Report", { enumerable: true, get: function () { return Moderation_1.Report; } });
var SuccessStory_1 = require("./SuccessStory");
Object.defineProperty(exports, "SuccessStory", { enumerable: true, get: function () { return SuccessStory_1.SuccessStory; } });
// Associations
UserProfile_1.UserProfile.hasOne(FamilyDetails_1.FamilyDetails, { foreignKey: "userProfileId" });
FamilyDetails_1.FamilyDetails.belongsTo(UserProfile_1.UserProfile, { foreignKey: "userProfileId" });
UserProfile_1.UserProfile.hasOne(HoroscopeDetails_1.HoroscopeDetails, { foreignKey: "userProfileId" });
HoroscopeDetails_1.HoroscopeDetails.belongsTo(UserProfile_1.UserProfile, { foreignKey: "userProfileId" });
UserProfile_1.UserProfile.hasOne(LocationLifestyle_1.LocationLifestyle, { foreignKey: "userProfileId" });
LocationLifestyle_1.LocationLifestyle.belongsTo(UserProfile_1.UserProfile, { foreignKey: "userProfileId" });
UserProfile_1.UserProfile.hasOne(EducationCareer_1.EducationCareer, { foreignKey: "userProfileId" });
EducationCareer_1.EducationCareer.belongsTo(UserProfile_1.UserProfile, { foreignKey: "userProfileId" });
UserProfile_1.UserProfile.hasOne(Badge_1.Badge, { foreignKey: "userProfileId" });
Badge_1.Badge.belongsTo(UserProfile_1.UserProfile, { foreignKey: "userProfileId" });
